name: flutter_shiny_blue
description: A simple bluetooth flutter plugin
version: 0.0.1
homepage: https://github.com/RythenGlyth/flutter_shiny_blue

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
	package: com.rythenglyth.shinyblue
        pluginClass: FlutterShinyBluePlugin
